import {Issue} from './types/Issue';

export default [
  {
    issuecode: 'nl/PO3 338',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '338',
    title: 'Een held als geen ander',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2023-04-12',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2023-04-12',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/04/nl_po3_338a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 337',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '337',
    title: 'Junglekoorts',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2023-03-15',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2023-03-15',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/04/nl_po3_337a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 336',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '336',
    title: 'De gestolen winter',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2023-02-15',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2023-02-15',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/04/nl_po3_336a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 335',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '335',
    title: 'De ongelukkige geluksvogel',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2023-01-18',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2023-01-18',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/02/nl_po3_335a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 334',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '334',
    title: 'De superheldenschool',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2022-12-21',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2022-12-21',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/01/nl_po3_334a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 333',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '333',
    title: 'Een onverwachte kerst',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2022-11-23',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2022-11-23',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/01/nl_po3_333a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 332',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '332',
    title: 'De microwereldreis',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2022-10-26',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2022-10-26',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/01/nl_po3_332a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 331',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '331',
    title: 'Het boevengenootschap',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2022-09-29',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2022-09-29',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/01/nl_po3_331a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 330',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '330',
    title: '19.999 mijlen onder zee',
    size: null,
    pages: '260',
    price: '5.95',
    printrun: null,
    attached: null,
    oldestdate: '2022-08-31',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2022-08-31',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/01/nl_po3_330a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
  {
    issuecode: 'nl/PO3 329',
    issuerangecode: null,
    publicationcode: 'nl/PO3',
    issuenumber: '329',
    title: 'Duel in de diepzee',
    size: null,
    pages: '260',
    price: 'EUR 5.95',
    printrun: null,
    attached: null,
    oldestdate: '2022-08-03',
    fullyindexed: true,
    issuecomment: null,
    error: false,
    filledoldestdate: '2022-08-03',
    locked: false,
    inxforbidden: false,
    inputfilecode: 1842,
    maintenanceteamcode: 'Team_nl',
    image_urls: [
      'https://inducks.org/hr.php?image=https://outducks.org/webusers/webusers/2023/01/nl_po3_329a_001.jpg',
    ],
    publication: {title: 'Donald Duck Pocket (3e reeks)'},
  },
] as unknown as Issue[];
